### ISSUE TITLE
Information on how to add custom wake words

### ISSUE THREAD

**Issue by taciturnaxolotl** [rhasspy/wyoming-porcupine1#1]
I believe this would be accomplished by mapping `wyoming_porcupine1/data/resources/en/linux` to a local folder on the host for docker, but would like to make sure. I would be willing to make a PR to add this to the README.

**Comment by chatziko** [comment]
wyoming-porcupine1 uses an old version of porcupine (v1) which does not need an access key and does not have usage restrictions. Models trained from console.picovoice.ai use the latest version so they are not compabile.

I was curious to see whether I can make v2 work, so I created an [experimental fork](https://github.com/chatziko/wyoming-porcupine/) which uses the latest version. Give it a try.

So far it seems to work. Of course you need an access key and there is the 3 devices restriction. But restart or updating the addon does not affect the counter (at least in my tests). And custom wake words work fine.

**Comment by taciturnaxolotl** [comment]
Thank you for creating that fork! Works great! I hadn't had time to migrate to core, so only just installed it yesterday.
