### ISSUE TITLE
Memory usage very high

### ISSUE THREAD

**Issue by bbrendon** [rhasspy/wyoming-porcupine1#2]
I added this to the docker stack and my server crashed within 24 hours because it ran out of memory. I'm 99% sure this was the cause. I had no way to verify at the time because I couldn't login to the host. Saved logging information verified it was memory the was the cause of the issue.

I set a memory limit and it now shows 630MB used. Is this normal?

**Comment by bbrendon** [comment]
Memory limit was set to 1gb. Usage went to 1gb and the process is no longer running so I suppose docker killed it.

**Comment by synesthesiam** [comment]
A memory leak was identified and should be fixed now :+1:
